### ISSUE TITLE
Dataset PixelFeature color scale and position scale

### ISSUE THREAD

**Issue by toonvds** [CYang0515/pytorch_ssn#4]
In dataset.py on line 108 there is a function called PixelFeature. What is the purpose of color scale and position scale? Also, as it is a scaling operation, does 1 represent a neutral operation?

**Comment by CYang0515** [comment]
I follow the setting of the original paper. The function called PixelFeature is to generate the inputs of network.  Color scale and position scale are to rescale the range of inputs.
